### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by Rebel-Monk** [pghilardi/atom-python-test#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0-beta3
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [atom-python-test](https://github.com/pghilardi/atom-python-test) package, v0.1.7
### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /C:/Users/Prashant/.atom/packages/atom-python-test/lib/atom-python-test.coffee:100

TypeError: Cannot read property 'file' of undefined
    at Object.module.exports.AtomPythonTest.runAllTests (file:///C:/Users/Prashant/.atom/packages/atom-python-test/lib/atom-python-test.coffee:86:26)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-python-test:run-all-tests (file:///C:/Users/Prashant/.atom/packages/atom-python-test/lib/atom-python-test.coffee:17:98)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Prashant\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Prashant\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Prashant\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Prashant\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\Prashant\AppData\Local\atom\app-1.8.0-beta3\resources\app.asar\src\application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:03.0 atom-python-test:run-all-tests (button.btn.btn-default.icon.icon-link-external)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
aligner-python, v1.0.1
atom-python-debugger, v0.3.4
atom-python-test, v0.1.7
atomic-chrome, v0.3.0
autocomplete-python, v1.7.2
autoprotocol-python, v2.0.0
language-python-mamba, v1.0.1
linter, v1.11.4
linter-python, v2.1.7
linter-python-pep257, v0.0.1
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0
MagicPython, v0.5.9
python-autopep8, v0.1.3
python-for-glyphs, v0.1.0
python-indent, v0.4.3
python-iresolve, v0.0.3
python-isort, v0.0.7
python-jedi, v0.3.6
python-snippets, v1.9.0
python-tools, v0.6.7
python-yapf, v0.10.0

# Dev
No dev packages
```

**Comment by pghilardi** [comment]
Hi Rebel-Monk,

Thanks for the error report. Could you describe the steps to reproduce this error?

Thanks,
Pedro

**Comment by pghilardi** [comment]
Unable to reproduce.
