### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by codehead1980** [pghilardi/atom-python-test#24]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-python-test](https://github.com/pghilardi/atom-python-test) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At C:\Users\HOME\.atom\packages\atom-python-test\lib\atom-python-test.coffee:159

TypeError: Cannot read property 'path' of null
    at Object.runAllProjectTests (/packages/atom-python-test/lib/atom-python-test.coffee:159:67)
    at /packages/atom-python-test/lib/atom-python-test.coffee:41:106)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.1/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.1/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:13 core:cancel (input.hidden-input)
     -2:11.7.0 editor:duplicate-lines (input.hidden-input)
     -2:10 editor:consolidate-selections (input.hidden-input)
     -2:10 core:cancel (input.hidden-input)
  2x -2:09.9.0 core:backspace (input.hidden-input)
 42x -2:07.9.0 intentions:highlight (input.hidden-input)
     -2:03.7.0 build:select-active-target (input.hidden-input)
     -2:02.5.0 core:backspace (input.hidden-input)
     -2:02.1.0 editor:consolidate-selections (input.hidden-input)
     -2:02.1.0 core:cancel (input.hidden-input)
     -1:38.5.0 kite:open-settings (input.hidden-input)
     -1:01.3.0 atom-clock:toggle (input.hidden-input)
     -0:51.1.0 atom-clock:utc-mode (input.hidden-input)
     -0:41.2.0 atom-python-test:run-all-tests (input.hidden-input)
     -0:25.7.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -0:15.5.0 atom-python-test:run-all-project-tests (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-eclipse-syntax 0.0.5 
atom-fix-path 0.1.0 
atom-python-package 0.7.1 
atom-python-run 0.9.5 
atom-python-test 0.9.0 
atom-runner 2.7.1 
autocomplete-modules 1.8.0 
autocomplete-python 1.10.5 
autocomplete-python-jedi 1.10.3-0 
build 0.69.0 
build-python 0.9.3 
busy-signal 1.4.3 
city-lights-syntax 1.1.4 
city-lights-ui 1.2.0 
colorblind-wombat-dark-syntax 0.6.0 
copy-path 0.4.2 
env-from-shell 0.3.0 
ide-python 0.3.0 
intentions 1.1.5 
jscs-fixer 1.3.0 
kite 0.58.0 
linter 2.2.0 
linter-erb 1.1.0 
linter-pylama 0.9.5 
linter-pylint 2.1.0 
linter-python 3.1.2 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
python-debugger 0.2.0 
python-indent 1.1.4 
python-tools 0.6.9 
run-python-simply 0.4.0 
script 3.17.3 
styri-syntax 0.1.1 
tree-view-copy-relative-path 1.2.0 
```

**Comment by pghilardi** [comment]
I am unable to reproduce this issue in the last version of Atom Python Test. Could you try again and report if it works now?
