### ISSUE TITLE
Uncaught TypeError: editor.getBuffer is not a function

### ISSUE THREAD

**Issue by nihal27** [pghilardi/atom-python-test#25]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-python-test](https://github.com/pghilardi/atom-python-test) package 0.9.0

### Stack Trace

Uncaught TypeError: editor.getBuffer is not a function

```
At C:\Users\Nihal\.atom\packages\atom-python-test\lib\atom-python-test.coffee:159

TypeError: editor.getBuffer is not a function
    at Object.runAllProjectTests (/packages/atom-python-test/lib/atom-python-test.coffee:159:51)
    at /packages/atom-python-test/lib/atom-python-test.coffee:41:106)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.1/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.1/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:30.3.0 core:paste (input.hidden-input)
     -9:22.5.0 core:save-as (input.hidden-input)
 10x -8:22.7.0 core:backspace (input.hidden-input)
     -2:01.7.0 atom-python-test:run-all-tests (ul.list-inline.tab-bar.inset-panel)
     -1:27 core:confirm (input.hidden-input)
     -0:20.3.0 atom-python-test:run-all-project-tests (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-css-clean 2.24.1 
atom-ide-ui 0.7.1 
atom-idiomatic-comments-css-snippets 0.1.0 
atom-python-run 0.9.5 
atom-python-test 0.9.0 
atom-runner 2.7.1 
autocomplete-python 1.10.5 
css-grid-snippets 1.1.0 
css-helper-snippets 0.3.0 
css-snippets 1.1.0 
css-specificity 0.2.2 
html-head-snippets 0.2.0 
html-to-css 0.2.2 
html-to-string 0.2.3 
htmlhint 1.1.4 
ide-css 0.2.0 
ide-html 0.4.1 
ide-python 0.4.0 
language-html5-subtlegradient 0.1.0 
linter 2.2.0 
linter-tidy 2.3.1 
linter-ui-default 1.6.10 
python-debugger 0.2.0 
python-snippets 1.9.0 
python-tools 0.6.9 
```

**Comment by fudongxiao** [comment]
How can I solve this problem?

**Comment by pghilardi** [comment]
I am unable to reproduce this issue in the last version of Atom Python Test. Could you try the last version of the plug-in and report if the problem still occurs?
