### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by iamh2o** [pghilardi/atom-python-test#35]
[Enter steps to reproduce:]

1. ...From command console chose run all tests.
2. ...from the command line 'pytest' completes and runs all 4 tests successfully.

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Mac OS X 10.15.7
**Thrown From**: [atom-python-test](https://github.com/pghilardi/atom-python-test) package 1.0.1

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At /Users/jmajor/.atom/packages/atom-python-test/lib/atom-python-test.js:65

TypeError: Cannot read property 'buffer' of undefined
    at runAllTests (/packages/atom-python-test/lib/atom-python-test.js:65:17)
    at HTMLElement.atomPythonTestRunAllTests (/packages/atom-python-test/lib/atom-python-test.js:28:11)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:352326)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:687184)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:556011)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:550890)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:352326)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1227728)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1223862)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:286651)
```

### Commands

```
     -9:44.8.0 core:confirm (input.hidden-input)
  5x -8:04.0 core:backspace (input.hidden-input)
     -7:06.9.0 atom-python-test:toggle-test-results (input.hidden-input)
  2x -5:45 core:backspace (input.hidden-input)
 32x -4:56.6.0 core:move-down (input.hidden-input)
     -4:43.8.0 core:backspace (input.hidden-input)
  2x -3:23.5.0 core:confirm (input.hidden-input)
  2x -1:26.1.0 console:toggle (div.package-detail)
     -1:10.8.0 script:close-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.atomic-emacs.find-visible)
     -1:05.3.0 console:toggle (atom-pane.pane.active)
     -0:41.5.0 command-palette:toggle (atom-pane.pane.active)
     -0:33.6.0 core:confirm (input.hidden-input)
     -0:33.6.0 atom-python-test:run-all-tests (atom-pane.pane.active)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.33.4 
atom-brackets-glow 0.6.0 
atom-clock 0.1.18 
atom-file-icons 0.7.1 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-console 0.0.2 
atom-ide-datatip 0.25.0 
atom-ide-debugger 0.0.3 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.1.0 
atom-ide-signature-help 0.16.0 
atom-isort 3.2.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-python-run 0.9.7 
atom-python-test 1.0.1 
atomic-emacs 0.15.0 
autocomplete-python 1.17.0 
busy-signal 2.0.1 
emacs-atom 0.1.0 
emacs-tab 0.2.0 
expose 0.15.0 
find-list 0.3.0 
folded-code-preview 0.2.5 
git-tabs 0.4.1 
hey-pane 1.2.0 
Hydrogen 2.16.3 
ide-python 1.9.6 
intentions 2.1.1 
kite 0.206.0 
linter 3.4.0 
linter-flake8 2.4.0 
linter-pycodestyle 2.1.3 
linter-pyflakes 0.3.2 
linter-ui-default 3.4.1 
markdown-preview-plus 4.11.1 
minimap 4.40.0 
minimap-lens 0.8.2 
minimap-linter 2.2.2 
minimap-pigments 0.2.2 
monokai 0.28.0 
night-owl-theme-ui 0.1.0 
preview-plus 1.2.7 
project-manager 3.3.8 
python-black 0.7.0 
python-indent 1.2.6 
python-tools 0.6.9 
script 3.32.2 
scroll-color 0.3.0 
scroll-through-time 0.3.1 
simple-flake8 0.10.0 
theme-set 0.2.1 
toggle-gutter 0.3.4 
tool-bar 1.4.4 
tool-bar-almighty 0.9.0 
tool-bar-atom 1.7.1 
toolbar-fusion 0.8.5 
wakatime 11.0.4 
```

**Comment by gbpeloton** [comment]
bump. same deal
